# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tsns_pb2 as tsns__pb2


class TinySocialNetworkServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Follow = channel.unary_unary(
        '/TinySocialNetworkService/Follow',
        request_serializer=tsns__pb2.ToggleFollow.SerializeToString,
        response_deserializer=tsns__pb2.ToggleFollow.FromString,
        )
    self.Unfollow = channel.unary_unary(
        '/TinySocialNetworkService/Unfollow',
        request_serializer=tsns__pb2.ToggleFollow.SerializeToString,
        response_deserializer=tsns__pb2.ToggleFollow.FromString,
        )
    self.List = channel.unary_unary(
        '/TinySocialNetworkService/List',
        request_serializer=tsns__pb2.ListUser.SerializeToString,
        response_deserializer=tsns__pb2.ReturnList.FromString,
        )
    self.Timeline = channel.stream_stream(
        '/TinySocialNetworkService/Timeline',
        request_serializer=tsns__pb2.Post.SerializeToString,
        response_deserializer=tsns__pb2.Post.FromString,
        )


class TinySocialNetworkServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Follow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Unfollow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Timeline(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TinySocialNetworkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Follow': grpc.unary_unary_rpc_method_handler(
          servicer.Follow,
          request_deserializer=tsns__pb2.ToggleFollow.FromString,
          response_serializer=tsns__pb2.ToggleFollow.SerializeToString,
      ),
      'Unfollow': grpc.unary_unary_rpc_method_handler(
          servicer.Unfollow,
          request_deserializer=tsns__pb2.ToggleFollow.FromString,
          response_serializer=tsns__pb2.ToggleFollow.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=tsns__pb2.ListUser.FromString,
          response_serializer=tsns__pb2.ReturnList.SerializeToString,
      ),
      'Timeline': grpc.stream_stream_rpc_method_handler(
          servicer.Timeline,
          request_deserializer=tsns__pb2.Post.FromString,
          response_serializer=tsns__pb2.Post.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TinySocialNetworkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
